-- MySQL Script generated by MySQL Workbench
-- Fri Mar 01 20:39:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyApplication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyApplication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyApplication` DEFAULT CHARACTER SET utf8 ;
USE `MyApplication` ;

-- -----------------------------------------------------
-- Table `MyApplication`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyApplication`.`Contact` (
  `idContacto` INT NOT NULL,
  `email_contact` VARCHAR(45) NOT NULL,
  `asunto` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `MyApplication`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyApplication`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Contact_idContacto` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Contact1_idx` (`Contact_idContacto` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Contact1`
    FOREIGN KEY (`Contact_idContacto`)
    REFERENCES `MyApplication`.`Contact` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `MyApplication`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyApplication`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `MyApplication`.`Rol_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyApplication`.`Rol_has_usuario` (
  `Rol_idRol` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Rol_idRol`, `Usuario_idUsuario`),
  INDEX `fk_Rol_has_usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Rol_has_usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `MyApplication`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol_has_usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `MyApplication`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
